def add_args(parser):
    parser.add_argument('--training_type', default="simulation")
    parser.add_argument('--dataset', default="unet")
    parser.add_argument('--data_cache_dir', default='')
    parser.add_argument('--client_number', default=2)
    parser.add_argument('--client_num_per_round', default=2)
    parser.add_argument('--comm_round', default=30)
    parser.add_argument('--epochs', default=5)
    parser.add_argument('--client_optimizer', default="Adam")
    parser.add_argument('--partition_alpha', type=float, default=0.5)
    parser.add_argument('--client_id_list', default="[]")
    parser.add_argument('--batch-size', type=int, default=4, metavar='N')
    parser.add_argument('--federated_optimizer', default="FedAvg")
    parser.add_argument('--lr', type=float, default=0.001)
    parser.add_argument('--partition_method', default=1e-4)
    parser.add_argument('--weight_decay', default=1e-8)
    parser.add_argument('--model', default="")
    parser.add_argument('--frequency_of_the_test', default=1)
    parser.add_argument('--using_gpu', default=True)
    parser.add_argument('--backend', default="sp")
    parser.add_argument('--enable_wandb', default=False)
    parser.add_argument('--wandb_key', default='ee0b5f53d949c84cee7decbe7a629e63fb2f8408')
    parser.add_argument('--wandb_entity', default='fedml-ai')
    parser.add_argument('--wandb_project', default='simulation')
    parser.add_argument('--run_name', default='fedml_torch_fedavg')
    args = parser.parse_args()
    return args
